[platformio]
default_envs = esp32-s3-n16r8

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.18
    bblanchon/ArduinoJson@^7.4.3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DBOARD_HAS_PSRAM

[env:native]
platform = native
test_framework = unity
test_build_src = false
build_flags =
    -D UNITY_INCLUDE_DOUBLE
